# Generated by Django 3.0.6 on 2021-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
